### ISSUE TITLE
`get` does not work on JPG files

### ISSUE THREAD

**Issue by slzarate** [dropbox/dbxcli#59] opened 2017-01-25 22:32 UTC
`./dbxcli get xxx.pdf` and `./dbxcli get xxx.png` both work, but `./dbxcli get xxx.jpg` is not working.

Error message is:
`Error: json: cannot unmarshal object into Go value of type files.IsMediaMetadata`

I've managed to reproduce this with different files of all types and the error message is always the same. `./dbxcli ls xxx.jpg` does work.

**Comment by diwakergupta** [comment] 2017-01-26 04:15
How bizarre! thanks for reporting @slzarate , will take a look.

**Comment by diwakergupta** [comment] 2017-01-26 22:29
@slzarate I can confirm (and repro) the bug. We need to fix the underlying Go SDK for Dropbox APIs. I'll update here when the bug has been fixed. Thanks for your patience!

**Comment by diwakergupta** [comment] 2017-02-14 00:38
@slzarate can you download the latest release (https://github.com/dropbox/dbxcli/releases/tag/v2.0.1) and try? I've verified the fix locally, but want to make sure it works for you before I close this out. Thanks!

**Comment by slzarate** [comment] 2017-02-14 00:50
@diwakergupta On both Mac and Linux I encounter no errors when downloading the various types of files I'm testing (PDF, JPG, PNG, TXT), but now the files are all empty.

**Comment by diwakergupta** [comment] 2017-02-14 03:47
Hmm @slzarate can you double check with the latest release? I don't see the same behavior:

```sh
$ ./dbxcli-darwin-amd64 version
dbxcli version: v2.0.1
SDK version: 1.0.0-beta
Spec version: 2dd2e0f

$ ./dbxcli-darwin-amd64 get -v test.jpg
2017/02/13 19:45:17 client.go:1126: arg: &{/test.jpg }
2017/02/13 19:45:17 client.go:1143: req: &{POST https://content.dropboxapi.com/2/files/download HTTP/1.1 1 1 map[Dropbox-Api-Arg:[{"path":"/test.jpg"}]] <nil> 0 [] false content.dropboxapi.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
...
Downloading 148 KiB/148 KiB

$ ls -lhrt test.jpg
-rw-r--r--  1 diwaker  849048494   148K Feb 13 19:45 test.jpg
```

**Comment by slzarate** [comment] 2017-02-14 17:45
@diwakergupta Aha... I think I see the problem. That was a mistake in my testing. However, I have uncovered another bug: if I do `get xxx.jpg > yyy.jpg` (as I was testing earlier), it actually creates two files in the folder, xxx.jpg and yyy.jpg. However, yyy.jpg is an empty file (zero bytes). (Should I create a separate issue for this? It does work if you do `get xxx.jpg > xxx.jpg`.)

```
$ ./dbx version
dbxcli version: v2.0.1
SDK version: 1.0.0-beta
Spec version: 2dd2e0f
$ ./dbx get helsinki.jpg > not_helsinki.jpg
Downloading 1.5 MiB/1.5 MiB
$ ls -sh
total 17008
13936 dbx		 3072 helsinki.jpg	    0 not_helsinki.jpg```

This bug is actually also present in v2.0.0:

```
$ ./dbx version
dbxcli version: v2.0.1
SDK version: 1.0.0-beta
Spec version: 2dd2e0f
$ ./dbx get cookbook.pdf > not_cookbook.pdf
Downloading 7.6 MiB/7.6 Mi
$ ls -sh
total 29456
15656 cookbook.pdf	13800 dbx		    0 not_cookbook.pdf
```

**Comment by diwakergupta** [comment] 2017-02-14 17:57
@slzarate makes sense. This is actually the intended behavior: `get` accepts a `<source>` and an optional `<target>`; if latter is missing, it uses the same name as the source in the local directory.

The "redirect" behavior you are trying to get from `get foo > bar` would only work if we write to stdout if no target was specified -- feel free to open a separate feature request for this. I'll go ahead and close this issue out as you are able to download JPGs.

**Closed by diwakergupta** 2017-02-14 17:57 UTC
Labels: bug
